### ISSUE TITLE
Small correction needed in readme example, because o3.get_eigen() returns a list

### ISSUE THREAD

**Issue by geosharma** [o3seespy/o3seespy#1]
Hi Maxim,

Thank you for your work and effort. This is excellent. I was keeping my eye on [xcfem](https://github.com/xcfem/xc) before I found your work. My interest is primarily geotechnical and I am learning OpenSees, from examples, only from personal interest, mainly because of Minjie Zhu's OpenSeesPy. I also recently found Gmsh, meshio, and Paraview in my quest to generate mesh and visualize displacements for a slope stability analysis.

It seems like ``o3.get_eigen(osi, solver='fullGenLapack', n=1)`` returns a list therefore ``angular_freq = o3.get_eigen(osi, solver='fullGenLapack', n=1) ** 0.5`` produces an error. Either you may need to make changes to the return statement in the code  or change the line in the example to something similar to 
``angular_freq = o3.get_eigen(osi, solver='fullGenLapack', n=1)[0] ** 0.5``

I installed o3seespy today with pip, but ``o3seespy.__version__`` returns module has not attribute ``'__version__'`` but pip tells me the version I have is 3.1.0.19.

Also in ``osi = o3.OpenSeesInstance(ndm=2, state=0)`` I was not able to figure out what ``state`` was for. I see that in site response example ``state=3`` when initializing opensees instance. I haven't seen ``state`` in OpenSees or OpenSeesPy examples thus far.

Once again thank you for your work.

**Comment by millen1m** [comment]
Hi geosharma,
Thanks for your feedback. Yes the examples from Minjie and collaborators are fantastic!

The issue related to eigen was different for mac OS but now I have fixed it so it will alway return a list - thanks.
I have also added the __version__ attribute to the package and updated the package to '3.1.0.20', note the 3.1 refers to the underlying C++ OpenSees code.

In regards to the state parameter, it is not explained anywhere since this feature is only in alpha, but if set state=3, then you can add the following lines to your script to see the underlying OpenSeespy commands, it is useful for debugging.

`
import o3seespy.extensions
o3.extensions.to_py_file(osi)
`

Also, I have created some examples using o3seespy in a new repository here:  https://github.com/o3seespy/o3seespy-examples, they are all data driven using the sfsimodels package. Also there is a meshing example that makes use of the sfsimodels mesh tool.

Finally, I have started a new plotting package called o3plot to provide rapid plotting of o3seespy.
